/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.springframework.boot") version ("2.3.3.RELEASE")
    id("io.spring.dependency-management") version ("1.0.10.RELEASE")
}


allprojects {
    group = "com.qiusuo"
    version = "1.0"
}

val springCloudVersion by extra("Hoxton.SR8")

configure(subprojects.filter {
    !it.name.equals("qiusuo-platform") && !it.name.equals("qiusuo-paymentservice")
}) {
    println(project.name)
    apply {
        plugin("java")
        plugin("org.springframework.boot")
        plugin("io.spring.dependency-management")
    }
    //this will import the cloud dependencies bom
    dependencyManagement {
        imports {
            mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
        }
    }

    repositories {
        mavenLocal()
        jcenter()
    }
}