management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081

spring:
  application:
    name: qiusuo-qaservice
  data:
    mongodb:
      uri: mongodb://qiusuo:qiusuo@localhost:27018/admin
security:
  basic:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka