package com.qiusuo.qaservice.graphql.provider;

import graphql.kickstart.tools.boot.GraphQLJavaToolsAutoConfiguration;
import graphql.kickstart.tools.boot.SchemaStringProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;

import java.util.ArrayList;
import java.util.List;


@Configuration
@AutoConfigureBefore({GraphQLJavaToolsAutoConfiguration.class})
public class QiusuoSchemaProvider implements SchemaStringProvider {

    /** This property is generated by the config server.*/
    @Value("${graphqls_list}")
    private String graphqlsList;

    @Autowired
    private Environment environment;

    @Override
    public List<String> schemaStrings() {
        List<String> schemaStrings = new ArrayList<>();
        String[] propertyNames = parseGraphqlsList(this.graphqlsList);
        for (String o : propertyNames) {
            schemaStrings.add(environment.getProperty(o));
        }
        return schemaStrings;
    }

    private static String[] parseGraphqlsList(String graphqlsList) {
        final String separator = ",";
        return graphqlsList.split(separator);
    }
}

