version: "3.7"
services:
    cassandra: 
        container_name: qiusuo-cassandra
        image: cassandra:latest
        ports:
            - '7000:7000'
            - '9042:9042'
        networks: 
            qiusuo-cluster:
        volumes:
            -  /Users/ryan.zheng/Karrier/qiusuo-backend/qiusuo-root/data/dev/cassandra:/var/lib/cassandra
            - /Users/ryan.zheng/Karrier/qiusuo-backend/qiusuo-root/config/dev/cassandra:/etc/cassandra

    mysql:
        container_name: 'tech-blogs-mysql'
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_PASSWORD: openlearner
            MYSQL_DATABASE: aiopenlearner
            MYSQL_USER: openlearner
            MYSQL_PASSWORD: 123456
        ports:
            - "4406:3306"
    
        networks: 
            - esnet
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

networks:
    qiusuo-cluster:
        ipam:
            config:
                - subnet: 172.20.0.0/16
