version: "3.7"
services:
    cassandra: 
        container_name: qiusuo-cassandra
        image: cassandra:latest
        ports:
            - '7000:7000'
            - '9042:9042'
        volumes:
            -  ../../data/dev/cassandra:/var/lib/cassandra
            -  ./cassandra:/etc/cassandra

    mysql:
        container_name: 'qiusuo-mysql'
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: qiusuo
            MYSQL_DATABASE: qiusuo
            MYSQL_USER: qiusuo
            MYSQL_PASSWORD: qiusuo
        ports:
            - "4406:3306"
        volumes:
            - ../../data/dev/mysql:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    redis:
        container_name: 'qiusuo-redis'
        image: 'redis:5.0'
        ports:
            - "6479:6379"
    elasticsearch:
        image: 'elasticsearch:6.7.1'
        container_name: 'qiusuo-elasticsearch'
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01,es02,es03
        ports:
            - "9500:9200"
        volumes:
            - ../../data/dev/elk:/var/lib/elasticsearch
            - ./elk/elasticsearch.yml:/etc/elasticsearch/config/elasticsearch.yml
networks:
    default:
        external:
            name: dev_qiusuo-cluster

