server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/{application}, classpath:config/{application}/schema
  application:
    name: config-service