server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:/home/ryan/Karrier/QiuSuo/qiusuo-backend/qiusuo-root/confsvr/src/main/resources/config/communityservice
