spring:
    data:
        cassandra:
            contact-points: 127.0.0.1
    session:
        store-type: redis

basic:
    load-balancing-policy:
        local-datacenter: datacenter1
qiusuo:
    relay:
        host: localhost
        port: 61613
